create or replace PROCEDURE STATYSTYKI
IS
  v_obiekty   NUMBER;
  NULL_STRING EXCEPTION;
  PRAGMA EXCEPTION_INIT(NULL_STRING, -06535);
  v_licznik NUMBER;
BEGIN
  v_licznik:=1;
  EXECUTE IMMEDIATE 'DROP TABLE WYNIKI_POKRYCIE';
  EXECUTE IMMEDIATE 'CREATE TABLE WYNIKI_POKRYCIE AS SELECT ID FROM V_POKRYCIE1 WHERE ID is null';
  EXECUTE IMMEDIATE 'ALTER TABLE WYNIKI_POKRYCIE ADD ILOSC NUMBER';
  EXECUTE IMMEDIATE 'DROP TABLE WYNIKI_BLAD';
  EXECUTE IMMEDIATE 'CREATE TABLE WYNIKI_BLAD AS SELECT ID FROM V_BLAD1 WHERE ID is null';
  EXECUTE IMMEDIATE 'ALTER TABLE WYNIKI_BLAD ADD ILOSC NUMBER';
  SELECT MAX(OBIEKT)INTO v_obiekty FROM WYNIK;
  FOR i IN 1..v_obiekty
  LOOP
    EXECUTE IMMEDIATE 'INSERT INTO WYNIKI_POKRYCIE (ID, ILOSC) VALUES ('||v_licznik||', (select count(*) from v_pokrycie'||v_licznik||'))';
    EXECUTE IMMEDIATE 'INSERT INTO WYNIKI_BLAD (ID, ILOSC) VALUES ('||v_licznik||', (select count(*) from v_blad'||v_licznik||'))';
    v_licznik:=v_licznik+1;
  END LOOP;
EXCEPTION
WHEN NULL_STRING THEN
  dbms_output.put_line('Zrobione');
END;