create or replace PROCEDURE USUN
AS
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE V_dane';
  EXECUTE IMMEDIATE 'create table v_dane as select * from dane';
EXECUTE IMMEDIATE 'ALTER TABLE v_dane
DROP COLUMN id';
  EXECUTE immediate 'DROP TABLE POM';
  execute immediate 'CREATE TABLE "T_ALGORITHM"."POM"( "DECYZJA" VARCHAR2(2000) DEFAULT 0,  
"KOLUMNA" VARCHAR2(2000) DEFAULT 0,  
"DLUGOSC_DECYZJI" VARCHAR2(2000) DEFAULT 0,   
"OBIEKT_ID" VARCHAR2(2000)  
) SEGMENT CREATION IMMEDIATE   
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING  
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)  
TABLESPACE "SYSTEM"';
execute immediate 'DROP TABLE DANE1';
execute immediate 'create table dane1 as select * from dane where 1<>1';
END USUN;